name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: ${{ https://gist.github.com/Sehi-02 }}
          TIMEZONE: Asia/Seoul
